//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem_ChiTiet
    {
        public string MaSinhVien { get; set; }
        public string MaHocKy { get; set; }
        public int SoThuTu { get; set; }
        public string MaMonHoc { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public Nullable<int> PhanTramKiemTra { get; set; }
        public Nullable<int> PhanTramThi { get; set; }
        public string DiemKiemTra { get; set; }
        public string DiemThiLanMot { get; set; }
        public string DiemTongKetHeMuoi { get; set; }
        public string DiemTongKetDiemChu { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual ThongTin ThongTin { get; set; }
    }
}
