//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem_TongQuat
    {
        public string MaSinhVien { get; set; }
        public string MaHocKy { get; set; }
        public string DiemTrungBinhHocKyHeMuoi { get; set; }
        public string DiemTrungBinhHocKyHeBon { get; set; }
        public string DiemTrungBinhTichLuyHeMuoi { get; set; }
        public string DiemTrungBinhTichLuyHeBon { get; set; }
        public string SoTinChiDat { get; set; }
        public string SoTinChiTichLuy { get; set; }
        public string DiemTrungBinhRenLuyenHocKy { get; set; }
        public string PhanLoaiDTBRenLuyenHocKy { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual ThongTin ThongTin { get; set; }
    }
}
