//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThi
    {
        public string MaSinhVien { get; set; }
        public string MaHocKy { get; set; }
        public Nullable<int> SoMonThi { get; set; }
        public int SoThuTu { get; set; }
        public string MaMonHoc { get; set; }
        public string GhepThi { get; set; }
        public string ToThi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NgayThi { get; set; }
        public string GioBatDau { get; set; }
        public Nullable<int> SoPhut { get; set; }
        public string Phong { get; set; }
        public string HinhThucThi { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual ThongTin ThongTin { get; set; }
    }
}
