//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXTKB_NhomMonHoc
    {
        public string MaMonHoc { get; set; }
        public string Nhom { get; set; }
        public int Thu { get; set; }
        public int TietBatDau { get; set; }
        public Nullable<int> SoTiet { get; set; }
    
        public virtual SXTKB_MonHoc SXTKB_MonHoc { get; set; }
    }
}
