//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public string MaSinhVien { get; set; }
        public string MaHocKy { get; set; }
        public string MaTuan { get; set; }
        public string MaMonHoc { get; set; }
        public string PhongHoc { get; set; }
        public string Thu { get; set; }
        public int TietBatDau { get; set; }
        public Nullable<int> SoTiet { get; set; }
        public string GiangVien { get; set; }
        public string Lop { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual Tuan Tuan { get; set; }
        public virtual ThongTin ThongTin { get; set; }
    }
}
