//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTDTEntities : DbContext
    {
        public TTDTEntities()
            : base("name=TTDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Diem_ChiTiet> Diem_ChiTiet { get; set; }
        public DbSet<Diem_TongQuat> Diem_TongQuat { get; set; }
        public DbSet<HeDaoTao> HeDaoTao { get; set; }
        public DbSet<HocKy> HocKy { get; set; }
        public DbSet<Khoa> Khoa { get; set; }
        public DbSet<KhoaHoc> KhoaHoc { get; set; }
        public DbSet<LichThi> LichThi { get; set; }
        public DbSet<MonHoc> MonHoc { get; set; }
        public DbSet<Nganh> Nganh { get; set; }
        public DbSet<SXTKB_MonHoc> SXTKB_MonHoc { get; set; }
        public DbSet<SXTKB_NhomMonHoc> SXTKB_NhomMonHoc { get; set; }
        public DbSet<Tuan> Tuan { get; set; }
        public DbSet<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
        public DbSet<ThongTin> ThongTin { get; set; }
    }
}
