//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_use.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuan
    {
        public Tuan()
        {
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public string MaTuan { get; set; }
        public string TenTuan { get; set; }
    
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
    }
}
